# Generated by Django 5.1.3 on 2024-12-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_team_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
