# Generated by Django 5.1.3 on 2024-12-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
