# Generated by Django 5.1.3 on 2024-12-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_alter_match_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_badge',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_badge',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
