# Generated by Django 5.1.3 on 2024-12-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_role_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
